version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://npm.cognitant.com
    username: ${{ secrets.NPM_USER }}
    password: ${{ secrets.NPM_PASS }} # Must be an unencoded password
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - 'npm-npmjs'
    schedule:
      interval: 'monthly'
